packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@auth/core": 0.37.4
  "@auth/drizzle-adapter": 1.7.4
  "@eslint/js": ^9.20.0
  "@t3-oss/env-core": ^0.12.0
  "@tailwindcss/vite": ^4.0.6
  "@tanstack/react-router": ^1.104.1
  "@tanstack/router-devtools": ^1.102.5
  "@tanstack/router-plugin": ^1.102.6
  "@types/node": ^22.13.2
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  "@vitejs/plugin-react-swc": ^3.8.0
  better-auth: ^1.1.17
  dotenv-cli: ^8.0.0
  drizzle-kit: ^0.30.4
  drizzle-orm: ^0.39.3
  drizzle-zod: ^0.7.0
  eslint: ^9.20.1
  eslint-config-prettier: ^10.0.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-turbo: ^2.4.2
  globals: ^15.15.0
  prettier: ^3.5.1
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^4.0.6
  tailwindcss-animate: ^1.0.7
  turbo: ^2.4.2
  typescript: ^5.7.3
  typescript-eslint: ^8.24.0
  vite: ^6.1.0
  zod: ^3.24.2
