packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@eslint/js": ^9.37.0
  "@hono/node-server": ^1.19.5
  "@orpc/client": ^1.9.3
  "@orpc/contract": ^1.9.3
  "@orpc/openapi": ^1.9.3
  "@orpc/openapi-client": ^1.9.3
  "@orpc/server": ^1.9.3
  "@orpc/tanstack-query": ^1.9.3
  "@orpc/valibot": ^1.9.3
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-dialog": ^1.1.15
  "@radix-ui/react-dropdown-menu": ^2.1.16
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-toast": ^1.2.15
  "@radix-ui/react-tooltip": ^1.2.8
  "@tailwindcss/vite": ^4.1.14
  "@tanstack/react-form": ^1.23.6
  "@tanstack/react-query": ^5.90.2
  "@tanstack/react-router": ^1.132.47
  "@tanstack/router-devtools": ^1.132.51
  "@tanstack/router-plugin": ^1.132.51
  "@types/eslint-config-prettier": ^6.11.3
  "@types/node": ^24.7.1
  "@types/pg": ^8.15.5
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.1
  "@vitejs/plugin-react-swc": ^4.1.0
  better-auth: ^1.3.27
  class-variance-authority: ^0.7.1
  dotenv-cli: ^10.0.0
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  drizzle-valibot: ^0.4.2
  eslint: ^9.37.0
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.5.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-turbo: ^2.5.8
  globals: ^16.4.0
  hono: ^4.9.10
  next-themes: ^0.4.6
  pg: ^8.16.3
  prettier: ^3.6.2
  radix-ui: ^1.4.3
  react: ^19.2.0
  react-dom: ^19.2.0
  shx: ^0.4.0
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.14
  tailwindcss-animate: ^1.0.7
  tsdown: ^0.15.6
  tsx: ^4.20.6
  turbo: ^2.5.8
  typescript: ^5.9.3
  typescript-eslint: ^8.46.0
  url-join: ^5.0.0
  valibot: ^1.1.0
  vite: ^7.1.9

ignoredBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: ">=0.25.0"
