packages:
  - apps/*
  - packages/*
  - tools/*
catalog:
  "@eslint/js": ^9.34.0
  "@hono/node-server": ^1.19.0
  "@radix-ui/react-avatar": ^1.1.10
  "@radix-ui/react-dialog": ^1.1.15
  "@radix-ui/react-dropdown-menu": ^2.1.16
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-toast": ^1.2.15
  "@radix-ui/react-tooltip": ^1.2.8
  "@tailwindcss/vite": ^4.1.12
  "@tanstack/react-form": ^1.19.2
  "@tanstack/react-query": ^5.85.5
  "@tanstack/react-router": ^1.131.28
  "@tanstack/router-devtools": ^1.131.28
  "@tanstack/router-plugin": ^1.131.28
  "@types/eslint-config-prettier": ^6.11.3
  "@types/node": ^24.3.0
  "@types/pg": ^8.15.5
  "@types/react": ^19.1.11
  "@types/react-dom": ^19.1.8
  "@vitejs/plugin-react-swc": ^4.0.1
  better-auth: ^1.3.7
  class-variance-authority: ^0.7.1
  dotenv-cli: ^10.0.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  drizzle-valibot: ^0.4.2
  eslint: ^9.34.0
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.5.6
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.6
  globals: ^16.3.0
  hono: ^4.9.4
  next-themes: ^0.4.6
  pg: ^8.16.3
  prettier: ^3.6.2
  radix-ui: ^1.4.3
  react: ^19.1.1
  react-dom: ^19.1.1
  shx: ^0.4.0
  sonner: ^2.0.7
  superjson: ^2.2.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  tailwindcss-animate: ^1.0.7
  tsup: ^8.5.0
  tsx: ^4.20.5
  turbo: ^2.5.6
  typescript: ^5.9.2
  typescript-eslint: ^8.41.0
  url-join: ^5.0.0
  valibot: ^1.1.0
  vite: ^7.1.3
ignoredBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: ">=0.25.0"
