packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.35.0
  '@hono/node-server': ^1.19.1
  '@orpc/client': ^1.8.7
  '@orpc/contract': ^1.8.7
  '@orpc/openapi': ^1.8.7
  '@orpc/openapi-client': ^1.8.7
  '@orpc/server': ^1.8.7
  '@orpc/tanstack-query': ^1.8.7
  '@orpc/valibot': ^1.8.7
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-toast': ^1.2.15
  '@radix-ui/react-tooltip': ^1.2.8
  '@tailwindcss/postcss': ^4.1.12
  '@tailwindcss/vite': ^4.1.13
  '@tanstack/react-form': ^1.19.4
  '@tanstack/react-query': ^5.87.1
  '@tanstack/react-router': ^1.131.36
  '@tanstack/router-devtools': ^1.131.36
  '@tanstack/router-plugin': ^1.131.36
  '@types/eslint-config-prettier': ^6.11.3
  '@types/mdx': ^2.0.13
  '@types/node': ^24.3.1
  '@types/pg': ^8.15.5
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  '@typescript-eslint/eslint-plugin': ^8.41.0
  '@vitejs/plugin-react-swc': ^4.0.1
  better-auth: ^1.3.9
  class-variance-authority: ^0.7.1
  dotenv-cli: ^10.0.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  drizzle-valibot: ^0.4.2
  eslint: ^9.35.0
  eslint-config-next: ^15.5.2
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.5.6
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.6
  fumadocs-core: 15.7.7
  fumadocs-mdx: 11.8.2
  fumadocs-ui: 15.7.7
  globals: ^16.3.0
  hono: ^4.9.6
  next: 15.5.2
  next-themes: ^0.4.6
  pg: ^8.16.3
  postcss: ^8.5.6
  prettier: ^3.6.2
  radix-ui: ^1.4.3
  react: ^19.1.1
  react-dom: ^19.1.1
  shx: ^0.4.0
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tailwindcss-animate: ^1.0.7
  tsdown: ^0.15.0
  tsx: ^4.20.5
  turbo: ^2.5.6
  typescript: ^5.9.2
  typescript-eslint: ^8.43.0
  url-join: ^5.0.0
  valibot: ^1.1.0
  vite: ^7.1.5

ignoredBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: '>=0.25.0'
