name: DEV:AWS API deploy

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'packages/**/**'
      - 'tools/**/**'
# TODO: 未実装
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOGE_FUGA: hogefuga
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Build api
        working-directory: apps/api
        run: pnpm build
      - name: Deploy to AWS
        run: echo 'deploy to AWS...'
